//! Fine-Tuning Pipeline for AGNOS Local Model Adaptation
//!
//! Manages the lifecycle of fine-tuning local LLMs for agent-specific tasks:
//! collecting training data, preparing datasets, configuring and tracking
//! fine-tuning jobs, and registering adapted models. The actual GPU training
//! happens externally — this module orchestrates the pipeline.

use std::collections::HashMap;

use anyhow::{bail, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tracing::{debug, info, warn};
use uuid::Uuid;

// ---------------------------------------------------------------------------
// ExampleSource
// ---------------------------------------------------------------------------

/// Origin of a training example.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ExampleSource {
    /// Explicit positive/negative feedback from a user.
    UserFeedback,
    /// Generated by the agent interacting with itself.
    AgentSelfPlay,
    /// Hand-curated dataset provided by a developer.
    CuratedDataset,
    /// Extracted from real agent conversation logs.
    ConversationLog,
}

impl std::fmt::Display for ExampleSource {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UserFeedback => write!(f, "UserFeedback"),
            Self::AgentSelfPlay => write!(f, "AgentSelfPlay"),
            Self::CuratedDataset => write!(f, "CuratedDataset"),
            Self::ConversationLog => write!(f, "ConversationLog"),
        }
    }
}

// ---------------------------------------------------------------------------
// TrainingExample
// ---------------------------------------------------------------------------

/// A single input/output pair used for fine-tuning.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingExample {
    pub example_id: String,
    pub agent_id: String,
    pub input: String,
    pub output: String,
    /// Quality score in the range 0.0–1.0 (higher is better).
    pub quality_score: Option<f64>,
    pub source: ExampleSource,
    pub created_at: DateTime<Utc>,
    pub metadata: HashMap<String, String>,
}

impl TrainingExample {
    pub fn new(
        agent_id: impl Into<String>,
        input: impl Into<String>,
        output: impl Into<String>,
        source: ExampleSource,
    ) -> Self {
        Self {
            example_id: Uuid::new_v4().to_string(),
            agent_id: agent_id.into(),
            input: input.into(),
            output: output.into(),
            quality_score: None,
            source,
            created_at: Utc::now(),
            metadata: HashMap::new(),
        }
    }

    pub fn with_quality(mut self, score: f64) -> Self {
        self.quality_score = Some(score.clamp(0.0, 1.0));
        self
    }
}

// ---------------------------------------------------------------------------
// DatasetStats
// ---------------------------------------------------------------------------

/// Aggregate statistics for a training dataset.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatasetStats {
    pub total_examples: usize,
    pub avg_input_length: f64,
    pub avg_output_length: f64,
    /// Bucketed quality distribution: "0.0-0.2", "0.2-0.4", etc.
    pub quality_distribution: HashMap<String, usize>,
    /// Count of examples per source type.
    pub source_distribution: HashMap<ExampleSource, usize>,
}

impl Default for DatasetStats {
    fn default() -> Self {
        Self {
            total_examples: 0,
            avg_input_length: 0.0,
            avg_output_length: 0.0,
            quality_distribution: HashMap::new(),
            source_distribution: HashMap::new(),
        }
    }
}

// ---------------------------------------------------------------------------
// TrainingDataset
// ---------------------------------------------------------------------------

/// A named collection of training examples for a specific agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingDataset {
    pub dataset_id: String,
    pub name: String,
    pub agent_id: String,
    pub examples: Vec<TrainingExample>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub stats: DatasetStats,
}

impl TrainingDataset {
    pub fn new(name: impl Into<String>, agent_id: impl Into<String>) -> Self {
        let now = Utc::now();
        Self {
            dataset_id: Uuid::new_v4().to_string(),
            name: name.into(),
            agent_id: agent_id.into(),
            examples: Vec::new(),
            created_at: now,
            updated_at: now,
            stats: DatasetStats::default(),
        }
    }

    /// Append an example and refresh stats.
    pub fn add_example(&mut self, example: TrainingExample) {
        self.examples.push(example);
        self.updated_at = Utc::now();
        self.stats = self.compute_stats();
    }

    /// Remove an example by ID. Returns `true` if found.
    pub fn remove_example(&mut self, example_id: &str) -> bool {
        let before = self.examples.len();
        self.examples.retain(|e| e.example_id != example_id);
        let removed = self.examples.len() < before;
        if removed {
            self.updated_at = Utc::now();
            self.stats = self.compute_stats();
        }
        removed
    }

    /// Return references to examples whose quality score meets the threshold.
    pub fn filter_by_quality(&self, min_score: f64) -> Vec<&TrainingExample> {
        self.examples
            .iter()
            .filter(|e| e.quality_score.unwrap_or(0.0) >= min_score)
            .collect()
    }

    /// Recompute dataset statistics from the current example set.
    pub fn compute_stats(&self) -> DatasetStats {
        let total = self.examples.len();
        if total == 0 {
            return DatasetStats::default();
        }

        let avg_input = self.examples.iter().map(|e| e.input.len()).sum::<usize>() as f64
            / total as f64;
        let avg_output = self.examples.iter().map(|e| e.output.len()).sum::<usize>() as f64
            / total as f64;

        let mut quality_dist: HashMap<String, usize> = HashMap::new();
        for e in &self.examples {
            let score = e.quality_score.unwrap_or(0.0);
            let bucket = if score < 0.2 {
                "0.0-0.2"
            } else if score < 0.4 {
                "0.2-0.4"
            } else if score < 0.6 {
                "0.4-0.6"
            } else if score < 0.8 {
                "0.6-0.8"
            } else {
                "0.8-1.0"
            };
            *quality_dist.entry(bucket.to_string()).or_insert(0) += 1;
        }

        let mut source_dist: HashMap<ExampleSource, usize> = HashMap::new();
        for e in &self.examples {
            *source_dist.entry(e.source).or_insert(0) += 1;
        }

        DatasetStats {
            total_examples: total,
            avg_input_length: avg_input,
            avg_output_length: avg_output,
            quality_distribution: quality_dist,
            source_distribution: source_dist,
        }
    }
}

// ---------------------------------------------------------------------------
// FineTuneMethod
// ---------------------------------------------------------------------------

/// Approach used for fine-tuning a model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum FineTuneMethod {
    /// Full parameter update — most expensive, highest quality.
    FullFineTune,
    /// Low-Rank Adaptation — efficient parameter-efficient fine-tuning.
    LoRA { rank: u32, alpha: f64 },
    /// Quantised LoRA — even lower VRAM via quantisation.
    QLoRA { rank: u32, alpha: f64, bits: u8 },
    /// Prefix-tuning — prepend learnable tokens to the input.
    Prefix { prefix_length: u32 },
}

impl FineTuneMethod {
    /// Estimated VRAM multiplier relative to base model size.
    pub fn vram_multiplier(&self) -> f64 {
        match self {
            Self::FullFineTune => 4.0,
            Self::LoRA { .. } => 1.2,
            Self::QLoRA { bits, .. } => {
                if *bits <= 4 {
                    0.5
                } else {
                    0.7
                }
            }
            Self::Prefix { .. } => 1.1,
        }
    }
}

impl std::fmt::Display for FineTuneMethod {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FullFineTune => write!(f, "FullFineTune"),
            Self::LoRA { rank, alpha } => write!(f, "LoRA(rank={}, alpha={})", rank, alpha),
            Self::QLoRA { rank, alpha, bits } => {
                write!(f, "QLoRA(rank={}, alpha={}, {}bit)", rank, alpha, bits)
            }
            Self::Prefix { prefix_length } => write!(f, "Prefix(len={})", prefix_length),
        }
    }
}

// ---------------------------------------------------------------------------
// FineTuneConfig
// ---------------------------------------------------------------------------

/// Configuration for a fine-tuning job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FineTuneConfig {
    pub base_model: String,
    pub dataset_id: String,
    pub learning_rate: f64,
    pub epochs: u32,
    pub batch_size: u32,
    pub max_sequence_length: u32,
    pub warmup_steps: u32,
    pub weight_decay: f64,
    pub method: FineTuneMethod,
    pub output_model_name: String,
}

impl FineTuneConfig {
    pub fn new(
        base_model: impl Into<String>,
        dataset_id: impl Into<String>,
        method: FineTuneMethod,
        output_model_name: impl Into<String>,
    ) -> Self {
        Self {
            base_model: base_model.into(),
            dataset_id: dataset_id.into(),
            learning_rate: 2e-5,
            epochs: 3,
            batch_size: 8,
            max_sequence_length: 2048,
            warmup_steps: 100,
            weight_decay: 0.01,
            method,
            output_model_name: output_model_name.into(),
        }
    }
}

// ---------------------------------------------------------------------------
// JobStatus
// ---------------------------------------------------------------------------

/// Lifecycle state of a fine-tuning job.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum JobStatus {
    Queued,
    Preparing,
    Training,
    Evaluating,
    Complete,
    Failed(String),
    Cancelled,
}

impl JobStatus {
    /// Whether a transition from `self` to `to` is allowed.
    pub fn valid_transition(&self, to: &JobStatus) -> bool {
        matches!(
            (self, to),
            (Self::Queued, Self::Preparing)
                | (Self::Queued, Self::Cancelled)
                | (Self::Queued, Self::Failed(_))
                | (Self::Preparing, Self::Training)
                | (Self::Preparing, Self::Failed(_))
                | (Self::Preparing, Self::Cancelled)
                | (Self::Training, Self::Evaluating)
                | (Self::Training, Self::Failed(_))
                | (Self::Training, Self::Cancelled)
                | (Self::Evaluating, Self::Complete)
                | (Self::Evaluating, Self::Failed(_))
                | (Self::Evaluating, Self::Cancelled)
        )
    }

    /// Whether the job is in a terminal state (no further transitions).
    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::Complete | Self::Failed(_) | Self::Cancelled)
    }
}

impl std::fmt::Display for JobStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "Queued"),
            Self::Preparing => write!(f, "Preparing"),
            Self::Training => write!(f, "Training"),
            Self::Evaluating => write!(f, "Evaluating"),
            Self::Complete => write!(f, "Complete"),
            Self::Failed(msg) => write!(f, "Failed({})", msg),
            Self::Cancelled => write!(f, "Cancelled"),
        }
    }
}

// ---------------------------------------------------------------------------
// JobProgress
// ---------------------------------------------------------------------------

/// Snapshot of fine-tuning progress for a running job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobProgress {
    pub current_epoch: u32,
    pub total_epochs: u32,
    pub current_step: u64,
    pub total_steps: u64,
    pub loss: f64,
    pub learning_rate: f64,
    pub elapsed_secs: u64,
    pub estimated_remaining_secs: u64,
}

impl JobProgress {
    /// Completion percentage (0.0–100.0).
    pub fn percentage(&self) -> f64 {
        if self.total_steps == 0 {
            return 0.0;
        }
        (self.current_step as f64 / self.total_steps as f64) * 100.0
    }
}

impl Default for JobProgress {
    fn default() -> Self {
        Self {
            current_epoch: 0,
            total_epochs: 0,
            current_step: 0,
            total_steps: 0,
            loss: 0.0,
            learning_rate: 0.0,
            elapsed_secs: 0,
            estimated_remaining_secs: 0,
        }
    }
}

// ---------------------------------------------------------------------------
// FineTuneJob
// ---------------------------------------------------------------------------

/// A single fine-tuning job tracked by the pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FineTuneJob {
    pub job_id: String,
    pub config: FineTuneConfig,
    pub status: JobStatus,
    pub created_at: DateTime<Utc>,
    pub started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub progress: JobProgress,
    pub error: Option<String>,
    pub output_model_path: Option<String>,
}

impl FineTuneJob {
    fn new(config: FineTuneConfig) -> Self {
        Self {
            job_id: Uuid::new_v4().to_string(),
            config,
            status: JobStatus::Queued,
            created_at: Utc::now(),
            started_at: None,
            completed_at: None,
            progress: JobProgress::default(),
            error: None,
            output_model_path: None,
        }
    }

    /// Attempt a status transition; returns an error on invalid transitions.
    fn transition(&mut self, to: JobStatus) -> Result<()> {
        if !self.status.valid_transition(&to) {
            bail!(
                "invalid job status transition: {} -> {}",
                self.status,
                to
            );
        }
        debug!(job_id = %self.job_id, from = %self.status, to = %to, "job status transition");
        self.status = to;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// VramEstimate
// ---------------------------------------------------------------------------

/// Estimated VRAM breakdown for a fine-tuning job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VramEstimate {
    pub model_vram_gb: f64,
    pub optimizer_vram_gb: f64,
    pub activation_vram_gb: f64,
    pub total_gb: f64,
}

/// Estimate VRAM requirements for fine-tuning a model.
///
/// `model_params_millions` is the number of model parameters in millions
/// (e.g. 7000 for a 7B model). Each parameter is assumed to be 2 bytes (fp16).
pub fn estimate_vram(config: &FineTuneConfig, model_params_millions: u64) -> VramEstimate {
    // Base model size in GB (fp16 = 2 bytes per param)
    let base_gb = (model_params_millions as f64 * 1_000_000.0 * 2.0) / 1_073_741_824.0;

    let (model_vram_gb, optimizer_vram_gb, activation_vram_gb) = match &config.method {
        FineTuneMethod::FullFineTune => {
            // Full: model + optimizer states (~2x) + activations (~1x)
            let model = base_gb;
            let optimizer = base_gb * 2.0;
            let activation = base_gb * 1.0;
            (model, optimizer, activation)
        }
        FineTuneMethod::LoRA { .. } => {
            // LoRA: full model loaded + small trainable fraction
            let model = base_gb;
            let optimizer = base_gb * 0.1;
            let activation = base_gb * 0.1;
            (model, optimizer, activation)
        }
        FineTuneMethod::QLoRA { bits, .. } => {
            // QLoRA: quantised model + small trainable fraction
            let quant_factor = if *bits <= 4 { 0.25 } else { 0.5 };
            let model = base_gb * quant_factor;
            let optimizer = base_gb * 0.1;
            let activation = base_gb * 0.1 * quant_factor;
            (model, optimizer, activation)
        }
        FineTuneMethod::Prefix { .. } => {
            // Prefix: full model + small prefix parameters
            let model = base_gb;
            let optimizer = base_gb * 0.05;
            let activation = base_gb * 0.05;
            (model, optimizer, activation)
        }
    };

    let total = model_vram_gb + optimizer_vram_gb + activation_vram_gb;

    VramEstimate {
        model_vram_gb,
        optimizer_vram_gb,
        activation_vram_gb,
        total_gb: total,
    }
}

// ---------------------------------------------------------------------------
// ModelMetrics
// ---------------------------------------------------------------------------

/// Evaluation metrics for a fine-tuned model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelMetrics {
    pub final_loss: f64,
    pub eval_loss: Option<f64>,
    pub perplexity: Option<f64>,
}

// ---------------------------------------------------------------------------
// FineTunedModel
// ---------------------------------------------------------------------------

/// A model produced by a completed fine-tuning job.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FineTunedModel {
    pub model_id: String,
    pub name: String,
    pub base_model: String,
    pub job_id: String,
    pub agent_id: String,
    pub created_at: DateTime<Utc>,
    pub size_bytes: u64,
    pub method: FineTuneMethod,
    pub metrics: ModelMetrics,
}

// ---------------------------------------------------------------------------
// ModelRegistry
// ---------------------------------------------------------------------------

/// Registry tracking all fine-tuned models.
#[derive(Debug, Default)]
pub struct ModelRegistry {
    models: Vec<FineTunedModel>,
}

impl ModelRegistry {
    pub fn new() -> Self {
        Self {
            models: Vec::new(),
        }
    }

    pub fn register_model(&mut self, model: FineTunedModel) -> Result<()> {
        if self.models.iter().any(|m| m.model_id == model.model_id) {
            bail!("model with id '{}' already exists", model.model_id);
        }
        info!(model_id = %model.model_id, name = %model.name, "registering fine-tuned model");
        self.models.push(model);
        Ok(())
    }

    pub fn get_model(&self, model_id: &str) -> Option<&FineTunedModel> {
        self.models.iter().find(|m| m.model_id == model_id)
    }

    pub fn models_for_agent(&self, agent_id: &str) -> Vec<&FineTunedModel> {
        self.models.iter().filter(|m| m.agent_id == agent_id).collect()
    }

    pub fn list_models(&self) -> &[FineTunedModel] {
        &self.models
    }

    /// Return the model with the lowest `final_loss` for the given agent.
    pub fn best_model_for_agent(&self, agent_id: &str) -> Option<&FineTunedModel> {
        self.models
            .iter()
            .filter(|m| m.agent_id == agent_id)
            .min_by(|a, b| {
                a.metrics
                    .final_loss
                    .partial_cmp(&b.metrics.final_loss)
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
    }
}

// ---------------------------------------------------------------------------
// PipelineStats
// ---------------------------------------------------------------------------

/// Aggregate statistics for the fine-tuning pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineStats {
    pub total_datasets: usize,
    pub total_examples: usize,
    pub total_jobs: usize,
    pub completed_jobs: usize,
    pub failed_jobs: usize,
    pub active_jobs: usize,
    pub average_training_time_secs: Option<f64>,
}

// ---------------------------------------------------------------------------
// FineTunePipeline
// ---------------------------------------------------------------------------

/// Minimum number of training examples required to submit a job.
const MIN_EXAMPLES: usize = 10;

/// Orchestrates the fine-tuning lifecycle: datasets, jobs, and model output.
pub struct FineTunePipeline {
    datasets: Vec<TrainingDataset>,
    jobs: Vec<FineTuneJob>,
    pub model_registry: ModelRegistry,
}

impl FineTunePipeline {
    pub fn new() -> Self {
        info!("initialising fine-tune pipeline");
        Self {
            datasets: Vec::new(),
            jobs: Vec::new(),
            model_registry: ModelRegistry::new(),
        }
    }

    // -- Dataset operations -------------------------------------------------

    /// Create a new empty dataset, returning its ID.
    pub fn create_dataset(
        &mut self,
        name: impl Into<String>,
        agent_id: impl Into<String>,
    ) -> Result<String> {
        let ds = TrainingDataset::new(name, agent_id);
        let id = ds.dataset_id.clone();
        info!(dataset_id = %id, "created training dataset");
        self.datasets.push(ds);
        Ok(id)
    }

    pub fn get_dataset(&self, dataset_id: &str) -> Option<&TrainingDataset> {
        self.datasets.iter().find(|d| d.dataset_id == dataset_id)
    }

    pub fn get_dataset_mut(&mut self, dataset_id: &str) -> Option<&mut TrainingDataset> {
        self.datasets.iter_mut().find(|d| d.dataset_id == dataset_id)
    }

    /// Add examples to a dataset; returns the count actually added.
    pub fn add_examples(
        &mut self,
        dataset_id: &str,
        examples: Vec<TrainingExample>,
    ) -> Result<usize> {
        let ds = self
            .get_dataset_mut(dataset_id)
            .ok_or_else(|| anyhow::anyhow!("dataset not found: {}", dataset_id))?;
        let count = examples.len();
        for ex in examples {
            ds.add_example(ex);
        }
        debug!(dataset_id = %dataset_id, count = count, "added examples to dataset");
        Ok(count)
    }

    // -- Job operations -----------------------------------------------------

    /// Validate config and enqueue a new fine-tuning job.
    pub fn submit_job(&mut self, config: FineTuneConfig) -> Result<String> {
        // Validate learning rate
        if config.learning_rate <= 0.0 || config.learning_rate > 1.0 {
            bail!(
                "learning rate must be in (0.0, 1.0], got {}",
                config.learning_rate
            );
        }

        // Validate epochs
        if config.epochs == 0 || config.epochs > 100 {
            bail!("epochs must be in [1, 100], got {}", config.epochs);
        }

        // Validate batch_size
        if config.batch_size == 0 {
            bail!("batch_size must be > 0, got {}", config.batch_size);
        }

        // Validate max_sequence_length
        if config.max_sequence_length == 0 {
            bail!(
                "max_sequence_length must be > 0, got {}",
                config.max_sequence_length
            );
        }

        // Validate dataset exists and has enough examples
        let ds = self
            .get_dataset(&config.dataset_id)
            .ok_or_else(|| anyhow::anyhow!("dataset not found: {}", config.dataset_id))?;

        if ds.examples.len() < MIN_EXAMPLES {
            bail!(
                "dataset has {} examples, minimum {} required",
                ds.examples.len(),
                MIN_EXAMPLES
            );
        }

        let job = FineTuneJob::new(config);
        let job_id = job.job_id.clone();
        info!(job_id = %job_id, "submitted fine-tune job");
        self.jobs.push(job);
        Ok(job_id)
    }

    pub fn get_job(&self, job_id: &str) -> Option<&FineTuneJob> {
        self.jobs.iter().find(|j| j.job_id == job_id)
    }

    fn get_job_mut(&mut self, job_id: &str) -> Option<&mut FineTuneJob> {
        self.jobs.iter_mut().find(|j| j.job_id == job_id)
    }

    /// Update progress on a running job.
    pub fn update_progress(&mut self, job_id: &str, progress: JobProgress) -> Result<()> {
        let job = self
            .get_job_mut(job_id)
            .ok_or_else(|| anyhow::anyhow!("job not found: {}", job_id))?;

        if job.status.is_terminal() {
            bail!("cannot update progress on terminal job {}", job_id);
        }

        // Auto-transition Queued -> Preparing -> Training on first progress update
        if job.status == JobStatus::Queued {
            job.transition(JobStatus::Preparing)?;
            job.transition(JobStatus::Training)?;
            job.started_at = Some(Utc::now());
        } else if job.status == JobStatus::Preparing {
            job.transition(JobStatus::Training)?;
            job.started_at = Some(Utc::now());
        }

        job.progress = progress;
        debug!(job_id = %job_id, pct = %job.progress.percentage(), "updated job progress");
        Ok(())
    }

    /// Mark a job as successfully completed and record the model path.
    pub fn complete_job(&mut self, job_id: &str, model_path: String) -> Result<()> {
        let job = self
            .get_job_mut(job_id)
            .ok_or_else(|| anyhow::anyhow!("job not found: {}", job_id))?;

        // Transition through Evaluating to Complete if needed
        if job.status == JobStatus::Training {
            job.transition(JobStatus::Evaluating)?;
        }
        job.transition(JobStatus::Complete)?;
        job.completed_at = Some(Utc::now());
        job.output_model_path = Some(model_path);
        info!(job_id = %job_id, "fine-tune job completed");
        Ok(())
    }

    /// Mark a job as failed with an error message.
    pub fn fail_job(&mut self, job_id: &str, error: String) -> Result<()> {
        let job = self
            .get_job_mut(job_id)
            .ok_or_else(|| anyhow::anyhow!("job not found: {}", job_id))?;

        if job.status.is_terminal() {
            bail!("job {} is already in terminal state {}", job_id, job.status);
        }

        job.transition(JobStatus::Failed(error.clone()))?;
        job.error = Some(error);
        job.completed_at = Some(Utc::now());
        warn!(job_id = %job_id, "fine-tune job failed");
        Ok(())
    }

    /// Cancel a non-terminal job.
    pub fn cancel_job(&mut self, job_id: &str) -> Result<()> {
        let job = self
            .get_job_mut(job_id)
            .ok_or_else(|| anyhow::anyhow!("job not found: {}", job_id))?;

        if job.status.is_terminal() {
            bail!("job {} is already in terminal state {}", job_id, job.status);
        }

        job.transition(JobStatus::Cancelled)?;
        job.completed_at = Some(Utc::now());
        info!(job_id = %job_id, "fine-tune job cancelled");
        Ok(())
    }

    /// Return all jobs that are not in a terminal state.
    pub fn active_jobs(&self) -> Vec<&FineTuneJob> {
        self.jobs.iter().filter(|j| !j.status.is_terminal()).collect()
    }

    /// Return all jobs whose dataset belongs to the given agent.
    pub fn jobs_for_agent(&self, agent_id: &str) -> Vec<&FineTuneJob> {
        let agent_dataset_ids: Vec<&str> = self
            .datasets
            .iter()
            .filter(|d| d.agent_id == agent_id)
            .map(|d| d.dataset_id.as_str())
            .collect();

        self.jobs
            .iter()
            .filter(|j| agent_dataset_ids.contains(&j.config.dataset_id.as_str()))
            .collect()
    }

    /// Aggregate pipeline statistics.
    pub fn pipeline_stats(&self) -> PipelineStats {
        let total_examples: usize = self.datasets.iter().map(|d| d.examples.len()).sum();
        let completed: Vec<&FineTuneJob> = self
            .jobs
            .iter()
            .filter(|j| j.status == JobStatus::Complete)
            .collect();
        let failed = self
            .jobs
            .iter()
            .filter(|j| matches!(j.status, JobStatus::Failed(_)))
            .count();
        let active = self.active_jobs().len();

        let avg_time = if completed.is_empty() {
            None
        } else {
            let total_secs: f64 = completed
                .iter()
                .filter_map(|j| {
                    let start = j.started_at?;
                    let end = j.completed_at?;
                    Some((end - start).num_seconds() as f64)
                })
                .sum();
            let count = completed
                .iter()
                .filter(|j| j.started_at.is_some() && j.completed_at.is_some())
                .count();
            if count > 0 {
                Some(total_secs / count as f64)
            } else {
                Some(0.0)
            }
        };

        PipelineStats {
            total_datasets: self.datasets.len(),
            total_examples,
            total_jobs: self.jobs.len(),
            completed_jobs: completed.len(),
            failed_jobs: failed,
            active_jobs: active,
            average_training_time_secs: avg_time,
        }
    }
}

impl Default for FineTunePipeline {
    fn default() -> Self {
        Self::new()
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // -- Helpers ------------------------------------------------------------

    fn make_example(agent: &str, source: ExampleSource) -> TrainingExample {
        TrainingExample::new(agent, "What is Rust?", "Rust is a systems language.", source)
    }

    fn make_example_with_quality(agent: &str, score: f64) -> TrainingExample {
        TrainingExample::new(
            agent,
            "input text",
            "output text",
            ExampleSource::UserFeedback,
        )
        .with_quality(score)
    }

    fn populated_dataset(agent: &str, n: usize) -> TrainingDataset {
        let mut ds = TrainingDataset::new("test-ds", agent);
        for i in 0..n {
            let mut ex = make_example(agent, ExampleSource::CuratedDataset);
            ex.quality_score = Some((i as f64) / (n as f64));
            ds.add_example(ex);
        }
        ds
    }

    fn pipeline_with_dataset(n_examples: usize) -> (FineTunePipeline, String) {
        let mut p = FineTunePipeline::new();
        let ds_id = p.create_dataset("ds", "agent-1").unwrap();
        let examples: Vec<_> = (0..n_examples)
            .map(|_| make_example("agent-1", ExampleSource::CuratedDataset))
            .collect();
        p.add_examples(&ds_id, examples).unwrap();
        (p, ds_id)
    }

    fn default_config(dataset_id: &str) -> FineTuneConfig {
        FineTuneConfig::new(
            "llama-7b",
            dataset_id,
            FineTuneMethod::LoRA {
                rank: 16,
                alpha: 32.0,
            },
            "my-model",
        )
    }

    // -- TrainingExample ----------------------------------------------------

    #[test]
    fn example_new_has_uuid() {
        let ex = make_example("a1", ExampleSource::UserFeedback);
        assert!(!ex.example_id.is_empty());
        assert_eq!(ex.agent_id, "a1");
        assert_eq!(ex.source, ExampleSource::UserFeedback);
    }

    #[test]
    fn example_with_quality_clamps() {
        let ex = TrainingExample::new("a", "i", "o", ExampleSource::UserFeedback).with_quality(1.5);
        assert_eq!(ex.quality_score, Some(1.0));

        let ex2 =
            TrainingExample::new("a", "i", "o", ExampleSource::UserFeedback).with_quality(-0.5);
        assert_eq!(ex2.quality_score, Some(0.0));
    }

    #[test]
    fn example_default_quality_is_none() {
        let ex = make_example("a1", ExampleSource::AgentSelfPlay);
        assert!(ex.quality_score.is_none());
    }

    // -- TrainingDataset CRUD -----------------------------------------------

    #[test]
    fn dataset_add_example() {
        let mut ds = TrainingDataset::new("ds1", "agent-1");
        assert_eq!(ds.examples.len(), 0);
        ds.add_example(make_example("agent-1", ExampleSource::UserFeedback));
        assert_eq!(ds.examples.len(), 1);
        assert_eq!(ds.stats.total_examples, 1);
    }

    #[test]
    fn dataset_remove_example() {
        let mut ds = TrainingDataset::new("ds1", "agent-1");
        let ex = make_example("agent-1", ExampleSource::UserFeedback);
        let id = ex.example_id.clone();
        ds.add_example(ex);
        assert!(ds.remove_example(&id));
        assert_eq!(ds.examples.len(), 0);
    }

    #[test]
    fn dataset_remove_nonexistent() {
        let mut ds = TrainingDataset::new("ds1", "agent-1");
        assert!(!ds.remove_example("does-not-exist"));
    }

    #[test]
    fn dataset_filter_by_quality() {
        let mut ds = TrainingDataset::new("ds1", "agent-1");
        ds.add_example(make_example_with_quality("a", 0.3));
        ds.add_example(make_example_with_quality("a", 0.7));
        ds.add_example(make_example_with_quality("a", 0.9));
        let high = ds.filter_by_quality(0.6);
        assert_eq!(high.len(), 2);
    }

    #[test]
    fn dataset_filter_by_quality_none_score() {
        let mut ds = TrainingDataset::new("ds1", "a");
        ds.add_example(make_example("a", ExampleSource::UserFeedback)); // no score
        ds.add_example(make_example_with_quality("a", 0.5));
        // None quality treated as 0.0 — only the 0.5 passes min=0.1
        let filtered = ds.filter_by_quality(0.1);
        assert_eq!(filtered.len(), 1);
    }

    // -- DatasetStats -------------------------------------------------------

    #[test]
    fn compute_stats_empty() {
        let ds = TrainingDataset::new("ds", "a");
        let stats = ds.compute_stats();
        assert_eq!(stats.total_examples, 0);
        assert_eq!(stats.avg_input_length, 0.0);
    }

    #[test]
    fn compute_stats_quality_distribution() {
        let ds = populated_dataset("a", 20);
        let stats = ds.compute_stats();
        assert_eq!(stats.total_examples, 20);
        // Should have entries across multiple buckets
        assert!(!stats.quality_distribution.is_empty());
        let total: usize = stats.quality_distribution.values().sum();
        assert_eq!(total, 20);
    }

    #[test]
    fn compute_stats_source_distribution() {
        let mut ds = TrainingDataset::new("ds", "a");
        ds.add_example(make_example("a", ExampleSource::UserFeedback));
        ds.add_example(make_example("a", ExampleSource::UserFeedback));
        ds.add_example(make_example("a", ExampleSource::ConversationLog));
        let stats = ds.compute_stats();
        assert_eq!(stats.source_distribution[&ExampleSource::UserFeedback], 2);
        assert_eq!(stats.source_distribution[&ExampleSource::ConversationLog], 1);
    }

    #[test]
    fn compute_stats_avg_lengths() {
        let mut ds = TrainingDataset::new("ds", "a");
        let mut ex1 = make_example("a", ExampleSource::CuratedDataset);
        ex1.input = "ab".into(); // len 2
        ex1.output = "abcd".into(); // len 4
        let mut ex2 = make_example("a", ExampleSource::CuratedDataset);
        ex2.input = "abcdef".into(); // len 6
        ex2.output = "ab".into(); // len 2
        ds.add_example(ex1);
        ds.add_example(ex2);
        let stats = ds.compute_stats();
        assert!((stats.avg_input_length - 4.0).abs() < 0.001);
        assert!((stats.avg_output_length - 3.0).abs() < 0.001);
    }

    // -- FineTuneMethod -----------------------------------------------------

    #[test]
    fn method_vram_multiplier_full() {
        assert!((FineTuneMethod::FullFineTune.vram_multiplier() - 4.0).abs() < 0.001);
    }

    #[test]
    fn method_vram_multiplier_lora() {
        let m = FineTuneMethod::LoRA {
            rank: 16,
            alpha: 32.0,
        };
        assert!((m.vram_multiplier() - 1.2).abs() < 0.001);
    }

    #[test]
    fn method_vram_multiplier_qlora_4bit() {
        let m = FineTuneMethod::QLoRA {
            rank: 16,
            alpha: 32.0,
            bits: 4,
        };
        assert!((m.vram_multiplier() - 0.5).abs() < 0.001);
    }

    #[test]
    fn method_vram_multiplier_qlora_8bit() {
        let m = FineTuneMethod::QLoRA {
            rank: 16,
            alpha: 32.0,
            bits: 8,
        };
        assert!((m.vram_multiplier() - 0.7).abs() < 0.001);
    }

    #[test]
    fn method_display() {
        assert_eq!(FineTuneMethod::FullFineTune.to_string(), "FullFineTune");
        let lora = FineTuneMethod::LoRA {
            rank: 8,
            alpha: 16.0,
        };
        assert!(lora.to_string().contains("LoRA"));
    }

    // -- FineTuneConfig defaults -------------------------------------------

    #[test]
    fn config_defaults() {
        let c = FineTuneConfig::new("base", "ds", FineTuneMethod::FullFineTune, "out");
        assert!((c.learning_rate - 2e-5).abs() < 1e-10);
        assert_eq!(c.epochs, 3);
        assert_eq!(c.batch_size, 8);
        assert_eq!(c.max_sequence_length, 2048);
        assert_eq!(c.warmup_steps, 100);
        assert!((c.weight_decay - 0.01).abs() < 1e-10);
    }

    // -- JobStatus state machine -------------------------------------------

    #[test]
    fn valid_transitions_queued() {
        let q = JobStatus::Queued;
        assert!(q.valid_transition(&JobStatus::Preparing));
        assert!(q.valid_transition(&JobStatus::Cancelled));
        assert!(q.valid_transition(&JobStatus::Failed("err".into())));
        assert!(!q.valid_transition(&JobStatus::Training));
        assert!(!q.valid_transition(&JobStatus::Complete));
    }

    #[test]
    fn valid_transitions_preparing() {
        let p = JobStatus::Preparing;
        assert!(p.valid_transition(&JobStatus::Training));
        assert!(p.valid_transition(&JobStatus::Failed("err".into())));
        assert!(p.valid_transition(&JobStatus::Cancelled));
        assert!(!p.valid_transition(&JobStatus::Queued));
        assert!(!p.valid_transition(&JobStatus::Complete));
    }

    #[test]
    fn valid_transitions_training() {
        let t = JobStatus::Training;
        assert!(t.valid_transition(&JobStatus::Evaluating));
        assert!(t.valid_transition(&JobStatus::Failed("err".into())));
        assert!(t.valid_transition(&JobStatus::Cancelled));
        assert!(!t.valid_transition(&JobStatus::Queued));
        assert!(!t.valid_transition(&JobStatus::Preparing));
    }

    #[test]
    fn valid_transitions_evaluating() {
        let e = JobStatus::Evaluating;
        assert!(e.valid_transition(&JobStatus::Complete));
        assert!(e.valid_transition(&JobStatus::Failed("err".into())));
        assert!(e.valid_transition(&JobStatus::Cancelled));
        assert!(!e.valid_transition(&JobStatus::Training));
    }

    #[test]
    fn terminal_states_have_no_transitions() {
        let terminal = vec![
            JobStatus::Complete,
            JobStatus::Failed("x".into()),
            JobStatus::Cancelled,
        ];
        for s in &terminal {
            assert!(s.is_terminal());
            assert!(!s.valid_transition(&JobStatus::Queued));
            assert!(!s.valid_transition(&JobStatus::Training));
        }
    }

    #[test]
    fn non_terminal_states() {
        assert!(!JobStatus::Queued.is_terminal());
        assert!(!JobStatus::Preparing.is_terminal());
        assert!(!JobStatus::Training.is_terminal());
        assert!(!JobStatus::Evaluating.is_terminal());
    }

    // -- JobProgress --------------------------------------------------------

    #[test]
    fn progress_percentage() {
        let p = JobProgress {
            current_step: 50,
            total_steps: 200,
            ..Default::default()
        };
        assert!((p.percentage() - 25.0).abs() < 0.001);
    }

    #[test]
    fn progress_percentage_zero_steps() {
        let p = JobProgress::default();
        assert!((p.percentage() - 0.0).abs() < 0.001);
    }

    #[test]
    fn progress_percentage_complete() {
        let p = JobProgress {
            current_step: 100,
            total_steps: 100,
            ..Default::default()
        };
        assert!((p.percentage() - 100.0).abs() < 0.001);
    }

    // -- Pipeline: dataset ops ----------------------------------------------

    #[test]
    fn pipeline_create_dataset() {
        let mut p = FineTunePipeline::new();
        let id = p.create_dataset("my-ds", "agent-1").unwrap();
        assert!(!id.is_empty());
        let ds = p.get_dataset(&id).unwrap();
        assert_eq!(ds.name, "my-ds");
        assert_eq!(ds.agent_id, "agent-1");
    }

    #[test]
    fn pipeline_get_nonexistent_dataset() {
        let p = FineTunePipeline::new();
        assert!(p.get_dataset("nope").is_none());
    }

    #[test]
    fn pipeline_add_examples() {
        let (p, ds_id) = pipeline_with_dataset(15);
        let ds = p.get_dataset(&ds_id).unwrap();
        assert_eq!(ds.examples.len(), 15);
    }

    #[test]
    fn pipeline_add_examples_unknown_dataset() {
        let mut p = FineTunePipeline::new();
        let result = p.add_examples("bad-id", vec![]);
        assert!(result.is_err());
    }

    // -- Pipeline: submit_job validation ------------------------------------

    #[test]
    fn submit_job_success() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let config = default_config(&ds_id);
        let job_id = p.submit_job(config).unwrap();
        assert!(!job_id.is_empty());
        let job = p.get_job(&job_id).unwrap();
        assert_eq!(job.status, JobStatus::Queued);
    }

    #[test]
    fn submit_job_bad_learning_rate_zero() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let mut config = default_config(&ds_id);
        config.learning_rate = 0.0;
        assert!(p.submit_job(config).is_err());
    }

    #[test]
    fn submit_job_bad_learning_rate_too_high() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let mut config = default_config(&ds_id);
        config.learning_rate = 1.5;
        assert!(p.submit_job(config).is_err());
    }

    #[test]
    fn submit_job_bad_learning_rate_negative() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let mut config = default_config(&ds_id);
        config.learning_rate = -0.001;
        assert!(p.submit_job(config).is_err());
    }

    #[test]
    fn submit_job_bad_epochs_zero() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let mut config = default_config(&ds_id);
        config.epochs = 0;
        assert!(p.submit_job(config).is_err());
    }

    #[test]
    fn submit_job_bad_epochs_too_many() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let mut config = default_config(&ds_id);
        config.epochs = 101;
        assert!(p.submit_job(config).is_err());
    }

    #[test]
    fn submit_job_unknown_dataset() {
        let mut p = FineTunePipeline::new();
        let config = default_config("nonexistent");
        assert!(p.submit_job(config).is_err());
    }

    #[test]
    fn submit_job_too_few_examples() {
        let (mut p, ds_id) = pipeline_with_dataset(5); // less than MIN_EXAMPLES
        let config = default_config(&ds_id);
        assert!(p.submit_job(config).is_err());
    }

    // -- Pipeline: job lifecycle --------------------------------------------

    #[test]
    fn job_update_progress() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let job_id = p.submit_job(default_config(&ds_id)).unwrap();
        let progress = JobProgress {
            current_epoch: 1,
            total_epochs: 3,
            current_step: 10,
            total_steps: 100,
            loss: 0.5,
            learning_rate: 2e-5,
            elapsed_secs: 60,
            estimated_remaining_secs: 540,
        };
        p.update_progress(&job_id, progress).unwrap();
        let job = p.get_job(&job_id).unwrap();
        assert_eq!(job.status, JobStatus::Training);
        assert!(job.started_at.is_some());
        assert!((job.progress.loss - 0.5).abs() < 0.001);
    }

    #[test]
    fn job_complete_lifecycle() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let job_id = p.submit_job(default_config(&ds_id)).unwrap();

        // Progress update transitions to Training
        p.update_progress(
            &job_id,
            JobProgress {
                current_step: 100,
                total_steps: 100,
                ..Default::default()
            },
        )
        .unwrap();

        // Complete transitions Training -> Evaluating -> Complete
        p.complete_job(&job_id, "/models/out".into()).unwrap();
        let job = p.get_job(&job_id).unwrap();
        assert_eq!(job.status, JobStatus::Complete);
        assert!(job.completed_at.is_some());
    }

    #[test]
    fn job_fail() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let job_id = p.submit_job(default_config(&ds_id)).unwrap();
        p.fail_job(&job_id, "OOM".into()).unwrap();
        let job = p.get_job(&job_id).unwrap();
        assert!(matches!(job.status, JobStatus::Failed(_)));
        assert_eq!(job.error, Some("OOM".into()));
    }

    #[test]
    fn job_cancel() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let job_id = p.submit_job(default_config(&ds_id)).unwrap();
        p.cancel_job(&job_id).unwrap();
        let job = p.get_job(&job_id).unwrap();
        assert_eq!(job.status, JobStatus::Cancelled);
    }

    #[test]
    fn job_cancel_already_complete() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let job_id = p.submit_job(default_config(&ds_id)).unwrap();
        p.update_progress(&job_id, JobProgress::default()).unwrap();
        p.complete_job(&job_id, "/m".into()).unwrap();
        assert!(p.cancel_job(&job_id).is_err());
    }

    #[test]
    fn job_fail_already_cancelled() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let job_id = p.submit_job(default_config(&ds_id)).unwrap();
        p.cancel_job(&job_id).unwrap();
        assert!(p.fail_job(&job_id, "err".into()).is_err());
    }

    #[test]
    fn update_progress_terminal_job() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let job_id = p.submit_job(default_config(&ds_id)).unwrap();
        p.cancel_job(&job_id).unwrap();
        assert!(p.update_progress(&job_id, JobProgress::default()).is_err());
    }

    #[test]
    fn job_unknown_id() {
        let p = FineTunePipeline::new();
        assert!(p.get_job("nonexistent").is_none());
    }

    #[test]
    fn update_progress_unknown_job() {
        let mut p = FineTunePipeline::new();
        assert!(p.update_progress("x", JobProgress::default()).is_err());
    }

    #[test]
    fn complete_unknown_job() {
        let mut p = FineTunePipeline::new();
        assert!(p.complete_job("x", "/m".into()).is_err());
    }

    #[test]
    fn fail_unknown_job() {
        let mut p = FineTunePipeline::new();
        assert!(p.fail_job("x", "e".into()).is_err());
    }

    #[test]
    fn cancel_unknown_job() {
        let mut p = FineTunePipeline::new();
        assert!(p.cancel_job("x").is_err());
    }

    // -- Pipeline: active_jobs & jobs_for_agent -----------------------------

    #[test]
    fn active_jobs_filters_terminal() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let j1 = p.submit_job(default_config(&ds_id)).unwrap();
        let _j2 = p.submit_job(default_config(&ds_id)).unwrap();
        p.cancel_job(&j1).unwrap();
        assert_eq!(p.active_jobs().len(), 1);
    }

    #[test]
    fn jobs_for_agent() {
        let mut p = FineTunePipeline::new();
        let ds1 = p.create_dataset("ds1", "agent-a").unwrap();
        let ds2 = p.create_dataset("ds2", "agent-b").unwrap();
        // Populate both
        let ex_a: Vec<_> = (0..12)
            .map(|_| make_example("agent-a", ExampleSource::CuratedDataset))
            .collect();
        let ex_b: Vec<_> = (0..12)
            .map(|_| make_example("agent-b", ExampleSource::CuratedDataset))
            .collect();
        p.add_examples(&ds1, ex_a).unwrap();
        p.add_examples(&ds2, ex_b).unwrap();

        p.submit_job(default_config(&ds1)).unwrap();
        p.submit_job(default_config(&ds1)).unwrap();
        p.submit_job(default_config(&ds2)).unwrap();

        assert_eq!(p.jobs_for_agent("agent-a").len(), 2);
        assert_eq!(p.jobs_for_agent("agent-b").len(), 1);
        assert_eq!(p.jobs_for_agent("agent-c").len(), 0);
    }

    // -- Pipeline stats -----------------------------------------------------

    #[test]
    fn pipeline_stats_empty() {
        let p = FineTunePipeline::new();
        let s = p.pipeline_stats();
        assert_eq!(s.total_datasets, 0);
        assert_eq!(s.total_examples, 0);
        assert_eq!(s.total_jobs, 0);
        assert!(s.average_training_time_secs.is_none());
    }

    #[test]
    fn pipeline_stats_with_data() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let j1 = p.submit_job(default_config(&ds_id)).unwrap();
        let j2 = p.submit_job(default_config(&ds_id)).unwrap();
        p.update_progress(&j1, JobProgress::default()).unwrap();
        p.complete_job(&j1, "/m".into()).unwrap();
        p.cancel_job(&j2).unwrap();

        let s = p.pipeline_stats();
        assert_eq!(s.total_datasets, 1);
        assert_eq!(s.total_examples, 15);
        assert_eq!(s.total_jobs, 2);
        assert_eq!(s.completed_jobs, 1);
        assert_eq!(s.active_jobs, 0);
    }

    // -- ModelRegistry ------------------------------------------------------

    #[test]
    fn registry_register_and_get() {
        let mut reg = ModelRegistry::new();
        let model = FineTunedModel {
            model_id: "m1".into(),
            name: "test-model".into(),
            base_model: "llama-7b".into(),
            job_id: "j1".into(),
            agent_id: "a1".into(),
            created_at: Utc::now(),
            size_bytes: 1024,
            method: FineTuneMethod::FullFineTune,
            metrics: ModelMetrics {
                final_loss: 0.3,
                eval_loss: Some(0.35),
                perplexity: Some(1.42),
            },
        };
        reg.register_model(model).unwrap();
        assert!(reg.get_model("m1").is_some());
        assert!(reg.get_model("m2").is_none());
    }

    #[test]
    fn registry_models_for_agent() {
        let mut reg = ModelRegistry::new();
        for (id, agent) in [("m1", "a1"), ("m2", "a1"), ("m3", "a2")] {
            reg.register_model(FineTunedModel {
                model_id: id.into(),
                name: format!("model-{}", id),
                base_model: "base".into(),
                job_id: "j".into(),
                agent_id: agent.into(),
                created_at: Utc::now(),
                size_bytes: 100,
                method: FineTuneMethod::FullFineTune,
                metrics: ModelMetrics {
                    final_loss: 0.5,
                    eval_loss: None,
                    perplexity: None,
                },
            }).unwrap();
        }
        assert_eq!(reg.models_for_agent("a1").len(), 2);
        assert_eq!(reg.models_for_agent("a2").len(), 1);
        assert_eq!(reg.models_for_agent("a3").len(), 0);
    }

    #[test]
    fn registry_list_models() {
        let mut reg = ModelRegistry::new();
        assert!(reg.list_models().is_empty());
        reg.register_model(FineTunedModel {
            model_id: "m1".into(),
            name: "n".into(),
            base_model: "b".into(),
            job_id: "j".into(),
            agent_id: "a".into(),
            created_at: Utc::now(),
            size_bytes: 0,
            method: FineTuneMethod::FullFineTune,
            metrics: ModelMetrics {
                final_loss: 0.1,
                eval_loss: None,
                perplexity: None,
            },
        }).unwrap();
        assert_eq!(reg.list_models().len(), 1);
    }

    #[test]
    fn registry_best_model_for_agent() {
        let mut reg = ModelRegistry::new();
        for (id, loss) in [("m1", 0.5), ("m2", 0.2), ("m3", 0.8)] {
            reg.register_model(FineTunedModel {
                model_id: id.into(),
                name: id.into(),
                base_model: "b".into(),
                job_id: "j".into(),
                agent_id: "a1".into(),
                created_at: Utc::now(),
                size_bytes: 0,
                method: FineTuneMethod::LoRA {
                    rank: 8,
                    alpha: 16.0,
                },
                metrics: ModelMetrics {
                    final_loss: loss,
                    eval_loss: None,
                    perplexity: None,
                },
            }).unwrap();
        }
        let best = reg.best_model_for_agent("a1").unwrap();
        assert_eq!(best.model_id, "m2");
    }

    #[test]
    fn registry_best_model_no_models() {
        let reg = ModelRegistry::new();
        assert!(reg.best_model_for_agent("a1").is_none());
    }

    // -- VRAM estimation ---------------------------------------------------

    #[test]
    fn vram_full_finetune() {
        let config = FineTuneConfig::new("base", "ds", FineTuneMethod::FullFineTune, "out");
        let est = estimate_vram(&config, 7000); // 7B params
        // Base model ~13 GB fp16, total ~4x = ~52 GB
        assert!(est.total_gb > 40.0);
        assert!(est.model_vram_gb > 10.0);
        assert!(est.optimizer_vram_gb > est.model_vram_gb); // 2x model
    }

    #[test]
    fn vram_lora() {
        let config = FineTuneConfig::new(
            "base",
            "ds",
            FineTuneMethod::LoRA {
                rank: 16,
                alpha: 32.0,
            },
            "out",
        );
        let est = estimate_vram(&config, 7000);
        // LoRA ~1.2x base = ~15.6 GB
        assert!(est.total_gb < 20.0);
        assert!(est.total_gb > 10.0);
    }

    #[test]
    fn vram_qlora_4bit() {
        let config = FineTuneConfig::new(
            "base",
            "ds",
            FineTuneMethod::QLoRA {
                rank: 16,
                alpha: 32.0,
                bits: 4,
            },
            "out",
        );
        let est = estimate_vram(&config, 7000);
        // QLoRA 4-bit should be significantly less than LoRA
        let lora_config = FineTuneConfig::new(
            "base",
            "ds",
            FineTuneMethod::LoRA {
                rank: 16,
                alpha: 32.0,
            },
            "out",
        );
        let lora_est = estimate_vram(&lora_config, 7000);
        assert!(est.total_gb < lora_est.total_gb);
    }

    #[test]
    fn vram_qlora_8bit_larger_than_4bit() {
        let config_4 = FineTuneConfig::new(
            "b",
            "d",
            FineTuneMethod::QLoRA {
                rank: 16,
                alpha: 32.0,
                bits: 4,
            },
            "o",
        );
        let config_8 = FineTuneConfig::new(
            "b",
            "d",
            FineTuneMethod::QLoRA {
                rank: 16,
                alpha: 32.0,
                bits: 8,
            },
            "o",
        );
        let est_4 = estimate_vram(&config_4, 7000);
        let est_8 = estimate_vram(&config_8, 7000);
        assert!(est_8.model_vram_gb > est_4.model_vram_gb);
    }

    #[test]
    fn vram_prefix() {
        let config = FineTuneConfig::new(
            "b",
            "d",
            FineTuneMethod::Prefix { prefix_length: 20 },
            "o",
        );
        let est = estimate_vram(&config, 7000);
        // Prefix ~1.1x base
        assert!(est.total_gb > 13.0);
        assert!(est.total_gb < 20.0);
    }

    // -- Edge cases ---------------------------------------------------------

    #[test]
    fn example_source_display() {
        assert_eq!(ExampleSource::UserFeedback.to_string(), "UserFeedback");
        assert_eq!(ExampleSource::AgentSelfPlay.to_string(), "AgentSelfPlay");
        assert_eq!(ExampleSource::CuratedDataset.to_string(), "CuratedDataset");
        assert_eq!(ExampleSource::ConversationLog.to_string(), "ConversationLog");
    }

    #[test]
    fn job_status_display() {
        assert_eq!(JobStatus::Queued.to_string(), "Queued");
        assert_eq!(JobStatus::Training.to_string(), "Training");
        assert_eq!(
            JobStatus::Failed("oops".into()).to_string(),
            "Failed(oops)"
        );
    }

    #[test]
    fn dataset_stats_refreshed_on_add_remove() {
        let mut ds = TrainingDataset::new("ds", "a");
        let ex = make_example_with_quality("a", 0.9);
        let id = ex.example_id.clone();
        ds.add_example(ex);
        assert_eq!(ds.stats.total_examples, 1);
        ds.remove_example(&id);
        assert_eq!(ds.stats.total_examples, 0);
    }

    #[test]
    fn submit_job_boundary_learning_rate_1() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let mut config = default_config(&ds_id);
        config.learning_rate = 1.0; // exactly 1.0 is allowed
        assert!(p.submit_job(config).is_ok());
    }

    #[test]
    fn submit_job_boundary_epochs_100() {
        let (mut p, ds_id) = pipeline_with_dataset(15);
        let mut config = default_config(&ds_id);
        config.epochs = 100; // exactly 100 is allowed
        assert!(p.submit_job(config).is_ok());
    }

    #[test]
    fn submit_job_exactly_min_examples() {
        let (mut p, ds_id) = pipeline_with_dataset(MIN_EXAMPLES);
        let config = default_config(&ds_id);
        assert!(p.submit_job(config).is_ok());
    }

    #[test]
    fn pipeline_default_trait() {
        let p = FineTunePipeline::default();
        assert_eq!(p.pipeline_stats().total_datasets, 0);
    }

    #[test]
    fn duplicate_examples_allowed() {
        let mut ds = TrainingDataset::new("ds", "a");
        let ex1 = make_example("a", ExampleSource::UserFeedback);
        let ex2 = make_example("a", ExampleSource::UserFeedback);
        ds.add_example(ex1);
        ds.add_example(ex2);
        // Duplicate content is fine — each has unique ID
        assert_eq!(ds.examples.len(), 2);
        assert_ne!(ds.examples[0].example_id, ds.examples[1].example_id);
    }
}
