use once_cell::sync::Lazy;
use regex::Regex;
use std::collections::HashMap;

/// Compiled regex patterns, shared across all Interpreter instances.
pub(crate) static PATTERNS: Lazy<HashMap<String, Regex>> = Lazy::new(|| {
    let mut p = HashMap::new();
    let mut r = |name: &str, pat: &str| {
        p.insert(name.to_string(), Regex::new(pat).unwrap());
    };
    r(
        "list",
        r"(?i)^(show|list|display|what|see)?\s*(me\s+)?(all\s+)?(files|directories|dirs|folders|contents?)?\s*(in\s+)?(.+)?$",
    );
    r(
        "show_file",
        r"(?i)^(show|display|view|read|cat|open|print)\s+(me\s+)?(the\s+)?(content|file|contents)?\s*(of\s+)?(.+)$",
    );
    r(
        "find",
        r"(?i)^(find|locate|search\s+for|look\s+for)\s+(files?\s+(named|called)?\s+)?(.+)(\s+in\s+(.+))?$",
    );
    r(
        "grep",
        r"(?i)^(search|grep|find)\s+(for\s+)?(.+?)\s+(in|within|inside)\s+(.+)$",
    );
    r(
        "cd",
        r"(?i)^(go\s+to|change\s+(to\s+)?|cd\s+(to\s+)?|switch\s+to)\s*(directory\s+)?(.+)$",
    );
    r(
        "mkdir",
        r"(?i)^(create|make|new)\s+(a\s+)?(new\s+)?(directory|folder)\s+(named|called)?\s*(.+)$",
    );
    r("copy", r"(?i)^(copy|duplicate)\s+(.+?)\s+(to|into)\s+(.+)$");
    r("move", r"(?i)^(move|rename)\s+(.+?)\s+(to|into|as)\s+(.+)$");
    r(
        "remove",
        r"(?i)^(remove|delete|rm)\s+(the\s+)?(file|directory|folder)?\s*(.+)$",
    );
    r(
        "ps",
        r"(?i)^(show|list|display|what|view)\s+(me\s+)?(all\s+)?(running\s+)?(processes|tasks|programs|apps)$",
    );
    r(
        "sysinfo",
        r"(?i)^(show|display|what|get|view)\s+(me\s+)?(system|computer|machine)\s*(info|information|status|stats)?$",
    );
    r(
        "du",
        r"(?i)^(how\s+much\s+)?(disk\s+)?(space|usage|size)\s+(is\s+)?(used\s+)?(by\s+)?(in\s+)?(.+)?$",
    );
    r(
        "install",
        r"(?i)^(install|add|get)\s+(package|program|software|app)?\s*(.+)$",
    );
    r(
        "audit",
        r"(?i)^(show|view|display|check)\s+(the\s+)?(audit|security)\s*(log|trail|history|entries)?(\s+for\s+(agent\s+)?(.+?))?(\s+(in|from)\s+(the\s+)?(last\s+)?(.+))?$",
    );
    r(
        "agent_info",
        r"(?i)^(show|list|view|display|what)\s+(me\s+)?(all\s+)?(running\s+)?(agents?|ai\s+agents?)\s*(status|info)?(\s+(.+))?$",
    );
    r(
        "service",
        r"(?i)^(list|show|start|stop|restart|status)\s+(the\s+)?(services?|daemons?)\s*(.+)?$",
    );
    r(
        "network_scan",
        r"(?i)^(scan\s+ports?\s+(?:on|for)\s+(.+)|ping\s+sweep\s+(.+)|lookup\s+dns\s+(?:for\s+)?(.+)|trace\s+route\s+to\s+(.+)|capture\s+packets?\s+(?:on|from)\s+(.+)|scan\s+web\s+servers?\s+(.+))$",
    );
    r(
        "network_extended",
        r"(?i)^(mass\s+scan\s+(.+)|arp\s+scan\s*(.+)?|network\s+diag(?:nostics?)?\s+(?:for\s+)?(.+)|detect\s+services?\s+(?:on\s+)?(.+)|fuzz\s+dir(?:ectories|s)?\s+(?:on\s+)?(.+)|vuln(?:erability)?\s+scan\s+(.+)|show\s+(?:open\s+)?sockets?|list\s+(?:network\s+)?connections?|enumerate\s+dns\s+(?:for\s+)?(.+)|deep\s+inspect\s+(?:traffic\s+)?(?:on\s+)?(.+)|monitor\s+bandwidth)$",
    );
    r(
        "journal",
        r"(?i)^(show|view|display|check)\s+(the\s+)?(journal|journald?|systemd)\s*(logs?|entries|messages)?(\s+for\s+(.+?))?(\s+since\s+(.+))?$",
    );
    r(
        "journal_alt",
        r"(?i)^(show|view|display)\s+(the\s+)?(last\s+(\d+)\s+)?(error|warning|critical|info|debug|notice|alert|emerg)?\s*(logs?|log\s+entries)(\s+for\s+(.+?))?(\s+since\s+(.+))?$",
    );
    r(
        "device_info",
        r"(?i)^(list|show|view|display)\s+(the\s+)?(all\s+)?(usb|block|net|pci|input|scsi)?\s*(devices?|hardware)(\s+(info|information|details))?(\s+for\s+(.+))?$",
    );
    r(
        "device_path",
        r"(?i)^(device|udev)\s+(info|information|details)\s+(for|on|about)\s+(.+)$",
    );
    r(
        "mount",
        r"(?i)^(list|show|display)\s+(the\s+)?(all\s+)?(fuse\s+)?(mounts?|mounted\s+filesystems?|filesystems?)$",
    );
    r(
        "unmount",
        r"(?i)^(unmount|umount|eject|fusermount\s+-u)\s+(.+)$",
    );
    r("mount_action", r"(?i)^mount\s+(.+?)\s+(on|at|to)\s+(.+)$");
    r(
        "boot",
        r"(?i)^(list|show|view|display)\s+(the\s+)?(boot\s+(entries|config|configuration|menu)|bootloader)$",
    );
    r(
        "boot_set",
        r"(?i)^set\s+(default\s+)?boot\s+(entry|default|timeout)\s+(to\s+)?(.+)$",
    );
    r(
        "update",
        r"(?i)^(check\s+for\s+updates?|apply\s+(system\s+)?updates?|rollback\s+(system\s+)?updates?|update\s+status|show\s+(current\s+)?version|system\s+update\s+(check|apply|rollback|status))$",
    );
    r(
        "question",
        r"(?i)^(what|who|when|where|why|how|is|are|can|do|does)\s+.+\??$",
    );
    r(
        "knowledge",
        r"(?i)^(search|find|look\s+up)\s+(in\s+)?(knowledge|kb|docs|documentation)\s+(for\s+)?(.+)$",
    );
    r(
        "rag_query",
        r"(?i)^(rag|retrieve|context)\s+(query|search|find|for)\s+(.+)$",
    );
    r("ark_install", r"(?i)^ark\s+install\s+(.+)$");
    r("ark_remove", r"(?i)^ark\s+(remove|uninstall)\s+(.+)$");
    r("ark_search", r"(?i)^ark\s+search\s+(.+)$");
    r("ark_info", r"(?i)^ark\s+(info|show)\s+(.+)$");
    r("ark_update", r"(?i)^ark\s+update$");
    r("ark_upgrade", r"(?i)^ark\s+upgrade(\s+(.+))?$");
    r("ark_status", r"(?i)^ark\s+status$");
    r(
        "marketplace_install",
        r"(?i)^(install|add)\s+(package|agent|app)\s+(.+)$",
    );
    r(
        "marketplace_uninstall",
        r"(?i)^(uninstall|remove)\s+(package|agent|app)\s+(.+)$",
    );
    r(
        "marketplace_search",
        r"(?i)^(search|find|browse)\s+(marketplace|market|store|packages|agents)\s+(for\s+)?(.+)$",
    );
    r(
        "marketplace_list",
        r"(?i)^(list|show)\s+(installed\s+)?(packages|marketplace|agents|apps)$",
    );
    r(
        "marketplace_update",
        r"(?i)^(update|upgrade)\s+(packages|agents|all)$",
    );
    r(
        "aequi_tax",
        r"(?i)^(show|what|get|estimate|calculate)\s+(my\s+)?(quarterly\s+)?tax\s*(estimate|liability)?(\s+(?:for\s+)?q?(\d))?$",
    );
    r(
        "aequi_schedule_c",
        r"(?i)^(show|get|preview|generate)\s+(my\s+)?schedule\s*c(\s+(?:for\s+)?(\d{4}))?$",
    );
    r(
        "aequi_import",
        r"(?i)^import\s+(bank\s+)?(statement|transactions?|ofx|qfx|csv)\s+(from\s+)?(.+)$",
    );
    r(
        "aequi_balance",
        r"(?i)^(show|get|what|view)\s+(my\s+)?(account\s+)?balance[s]?$",
    );
    r(
        "aequi_receipts",
        r"(?i)^(show|list|view)\s+(my\s+)?(pending\s+|reviewed\s+|unreviewed\s+)?receipts$",
    );
    r(
        "task_list",
        r"(?i)^(show|list|view)\s+(my\s+)?tasks(\s+(?:that are\s+|in\s+|with status\s+)(\w+))?$",
    );
    r(
        "task_create",
        r"(?i)^(create|add|new)\s+task[:\s]+(.+?)(\s+priority\s+(low|medium|high))?$",
    );
    r(
        "task_update",
        r"(?i)^(mark|update|set)\s+task\s+(\S+)\s+(?:as\s+|status\s+(?:to\s+)?)(\w+)$",
    );
    r(
        "ritual_check",
        r"(?i)^(?:show|check|how are)\s+(?:my\s+)?(?:rituals|habits)(\s+today|\s+(\d{4}-\d{2}-\d{2}))?$",
    );
    r(
        "productivity_stats",
        r"(?i)^(?:show\s+)?(?:my\s+)?(?:productivity|stats|statistics|analytics)(\s+(daily|weekly|monthly|this week|this month))?$",
    );
    // --- Agnostic QA platform intents ---
    r(
        "agnostic_run",
        r"(?i)^(?:agnostic\s+)?run\s+(?:test\s+)?suite\s+(.+?)(\s+(?:on|against|for)\s+(.+))?$",
    );
    r(
        "agnostic_status",
        r"(?i)^(?:agnostic\s+)?test\s+(?:run\s+)?status\s+(?:for\s+)?(\S+)$",
    );
    r(
        "agnostic_report",
        r"(?i)^(?:agnostic\s+)?test\s+report\s+(?:for\s+)?(\S+)(\s+(?:as\s+|format\s+)(\w+))?$",
    );
    r(
        "agnostic_list_suites",
        r"(?i)^(?:agnostic\s+)?(?:list|show)\s+(?:test\s+)?suites?(\s+(?:in\s+|category\s+)?(\w+))?$",
    );
    r(
        "agnostic_agents",
        r"(?i)^(?:agnostic\s+)?(?:qa\s+)?agent\s+status(\s+(?:for\s+)?(\S+))?$",
    );
    // --- Delta code hosting intents ---
    r(
        "delta_create_repo",
        r"(?i)^delta\s+create[\s-]+(repo|repository)\s+(\S+)(\s+(.+))?$",
    );
    r(
        "delta_list_repos",
        r"(?i)^delta\s+(list|show)\s+(repos|repositories)$",
    );
    r(
        "delta_pr",
        r"(?i)^delta\s+(pr|pull[\s-]?request)\s+(list|create|merge|close)(\s+(?:in\s+|for\s+)?(\S+))?(\s+(.+))?$",
    );
    r(
        "delta_push",
        r"(?i)^delta\s+push(\s+(\S+))?(\s+(?:branch\s+)?(\S+))?$",
    );
    r(
        "delta_ci",
        r"(?i)^delta\s+(ci|pipeline|build)\s+(status|logs?)(\s+(?:for\s+|in\s+)?(\S+))?$",
    );
    // --- Edge fleet management intents ---
    r(
        "edge_list",
        r"(?i)^(?:edge\s+)?(list|show)\s+(?:edge\s+)?nodes?(\s+(?:status\s+)?(\S+))?$",
    );
    r(
        "edge_deploy",
        r"(?i)^(?:edge\s+)?deploy\s+(?:to\s+edge\s+)?(.+?)(?:\s+(?:on|to)\s+(?:node\s+)?(\S+))?$",
    );
    r(
        "edge_update",
        r"(?i)^(?:edge\s+update\s+(?:edge\s+)?(?:node\s+)?(\S+)|update\s+(?:edge\s+)?node\s+(\S+))(?:\s+(?:to\s+)?(?:version\s+)?(\S+))?$",
    );
    r(
        "edge_health",
        r"(?i)^(?:edge\s+)?(health|status)\s+(?:of\s+)?(?:(?:edge\s+)?(?:node\s+)?(\S+)|(?:fleet|all|nodes))$",
    );
    r(
        "edge_decommission",
        r"(?i)^(?:edge\s+)?decommission\s+(?:edge\s+)?(?:node\s+)?(\S+)$",
    );
    // --- Shruti DAW intents ---
    r(
        "shruti_session",
        r"(?i)^shruti\s+(session|project)\s+(create|open|save|close|info|list)(\s+(.+))?$",
    );
    r(
        "shruti_track",
        r"(?i)^shruti\s+(add|remove|list|rename)\s+(track|tracks)(\s+(\S+))?(\s+(?:type|kind)\s+(audio|midi|synth|instrument|bus))?$",
    );
    r(
        "shruti_mixer",
        r"(?i)^shruti\s+mix(?:er)?\s+(\S+)(\s+(?:gain|volume)\s+(-?\d+(?:\.\d+)?))?(\s+mute)?(\s+solo)?$",
    );
    r(
        "shruti_transport",
        r"(?i)^shruti\s+(play|pause|stop|seek|set[\s_]?tempo|status|record)(\s+(.+))?$",
    );
    r(
        "shruti_export",
        r"(?i)^shruti\s+export(?:\s+(?:to|as)\s+(.+?))?(\s+(?:format|as)\s+(wav|flac|mp3|aac|ogg))?$",
    );
    // --- Tazama video editor intents ---
    r(
        "tazama_project",
        r"(?i)^tazama\s+(project|video)\s+(create|open|save|close|info|list)(\s+(.+))?$",
    );
    r(
        "tazama_timeline",
        r"(?i)^tazama\s+(add|remove|split|trim|list|reorder)\s+(clip|clips)(\s+(\S+))?(\s+(?:at|position)\s+(\d+(?:\.\d+)?))?$",
    );
    r(
        "tazama_effects",
        r"(?i)^tazama\s+(apply|remove|list|preview)\s+(effect|effects|transition|transitions)(\s+(?:type\s+)?(transition|color_grade|filter|text_overlay))?(\s+(?:on|to)\s+(\S+))?$",
    );
    r(
        "tazama_ai",
        r"(?i)^tazama\s+(scene[\s_]?detect|auto[\s_]?cut|subtitle[\s_]?gen|style[\s_]?transfer|color[\s_]?grade|smart[\s_]?transition)(\s+(.+))?$",
    );
    r(
        "tazama_export",
        r"(?i)^tazama\s+export(?:\s+(?:to|as)\s+(.+?))?(\s+(?:format|as)\s+(mp4|webm|mov|avi|mkv))?$",
    );
    // --- Rasa image editor intents ---
    r(
        "rasa_canvas",
        r"(?i)^rasa\s+(canvas|image)\s+(create|open|save|close|info|list)(\s+(.+))?$",
    );
    r(
        "rasa_layers",
        r"(?i)^rasa\s+(add|remove|reorder|merge|list|duplicate)\s+(layer|layers)(\s+(\S+))?(\s+(?:type|kind)\s+(raster|vector|text|adjustment))?$",
    );
    r(
        "rasa_tools",
        r"(?i)^rasa\s+(brush|select|crop|resize|transform|fill)(\s+(.+))?$",
    );
    r(
        "rasa_ai",
        r"(?i)^rasa\s+(inpaint|upscale|remove[\s_]?bg|gen[\s_]?fill|style[\s_]?transfer|text[\s_]?to[\s_]?image|smart[\s_]?select)(\s+(.+))?$",
    );
    r(
        "rasa_export",
        r"(?i)^rasa\s+export(?:\s+(?:to|as)\s+(.+?))?(\s+(?:format|as)\s+(png|jpg|webp|svg|tiff|psd))?$",
    );
    // --- Mneme knowledge base intents ---
    r(
        "mneme_notebook",
        r"(?i)^mneme\s+(notebook|notebooks)\s+(create|open|delete|list|info)(\s+(.+))?$",
    );
    r(
        "mneme_notes",
        r"(?i)^mneme\s+(create|edit|delete|list|get)\s+(note|notes)(\s+(.+))?(\s+(?:in|notebook)\s+(\S+))?$",
    );
    r(
        "mneme_search",
        r"(?i)^mneme\s+search\s+(.+?)(\s+(?:mode|using)\s+(keyword|semantic|hybrid))?$",
    );
    r(
        "mneme_ai",
        r"(?i)^mneme\s+(summarize|extract[\s_]?concepts|auto[\s_]?link|generate|translate)(\s+(?:note\s+)?(\S+))?$",
    );
    r(
        "mneme_graph",
        r"(?i)^mneme\s+graph\s+(view|connections|suggest[\s_]?links|stats)(\s+(?:node\s+)?(\S+))?$",
    );
    // Synapse LLM management
    r(
        "synapse_models",
        r"(?i)^synapse\s+(model|models)\s+(download|delete|list|info)(\s+(.+?))?(\s+(?:from|source)\s+(huggingface|ollama|local))?$",
    );
    r(
        "synapse_serve",
        r"(?i)^synapse\s+(serve|serving)\s+(start|stop|status|list)(\s+(.+))?$",
    );
    r(
        "synapse_finetune",
        r"(?i)^synapse\s+(finetune|fine[\s_]?tune|train)\s+(start|status|cancel|list)(\s+(.+?))?(\s+(?:method|using)\s+(lora|qlora|full|dpo|rlhf))?$",
    );
    r(
        "synapse_chat",
        r"(?i)^synapse\s+(chat|ask|infer|complete|generate)\s+(?:with\s+)?(\S+)(\s+(.+))?$",
    );
    r("synapse_status", r"(?i)^synapse\s+(status|health|gpu)$");
    r(
        "synapse_benchmark",
        r"(?i)^synapse\s+(benchmark|bench|compare)\s+(run|compare|list|status)(\s+(.+))?$",
    );
    r(
        "synapse_quantize",
        r"(?i)^synapse\s+(quantize|quant|convert)\s+(start|status|list|cancel)(\s+(.+?))?(\s+(?:format|as)\s+(gguf|gptq|awq|bnb))?$",
    );
    // BullShift trading
    r(
        "bullshift_portfolio",
        r"(?i)^(?:bullshift|trading)\s+(portfolio|positions|pnl|p&l|holdings|balance)\s*(summary|history)?(\s+(?:for|period)\s+(1d|1w|1m|3m|1y|all))?$",
    );
    r(
        "bullshift_orders",
        r"(?i)^(?:bullshift|trading)\s+(order|orders)\s+(place|cancel|list|status)(\s+(.+?))?(\s+(buy|sell))?$",
    );
    r(
        "bullshift_market",
        r"(?i)^(?:bullshift|trading)\s+(quote|search|watchlist|history|market|price)\s*(\S+)?$",
    );
    r(
        "bullshift_alerts",
        r"(?i)^(?:bullshift|trading)\s+(alert|alerts)\s+(set|remove|list|triggered)(\s+(.+))?$",
    );
    r(
        "bullshift_strategy",
        r"(?i)^(?:bullshift|trading)\s+(strategy|strategies)\s+(list|start|stop|backtest|status)(\s+(.+))?$",
    );
    r(
        "bullshift_accounts",
        r"(?i)^(?:bullshift|trading)\s+(account|accounts)\s+(list|switch|status|info)(\s+(.+))?$",
    );
    r(
        "bullshift_history",
        r"(?i)^(?:bullshift|trading)\s+(history|trades|dividends|tax[\s_]?report)\s*(export)?(\s+(?:period|for)\s+(1d|1w|1m|3m|1y|all))?$",
    );
    // SecureYeoman AI platform
    r(
        "yeoman_agents",
        r"(?i)^(?:yeoman|secureyeoman)\s+(agent|agents)\s+(list|deploy|stop|status|info)(\s+(.+))?$",
    );
    r(
        "yeoman_tasks",
        r"(?i)^(?:yeoman|secureyeoman)\s+(task|tasks)\s+(assign|list|status|cancel)(\s+(.+))?$",
    );
    r(
        "yeoman_tools",
        r"(?i)^(?:yeoman|secureyeoman)\s+(tool|tools)\s+(list|search|info|categories)(\s+(.+))?$",
    );
    r(
        "yeoman_integrations",
        r"(?i)^(?:yeoman|secureyeoman)\s+(integration|integrations)\s+(list|enable|disable|status)(\s+(.+))?$",
    );
    r(
        "yeoman_status",
        r"(?i)^(?:yeoman|secureyeoman)\s+(status|health)$",
    );
    r(
        "yeoman_logs",
        r"(?i)^(?:yeoman|secureyeoman)\s+(log|logs)\s+(query|stream|tail|search)(\s+(.+))?$",
    );
    r(
        "yeoman_workflows",
        r"(?i)^(?:yeoman|secureyeoman)\s+(workflow|workflows)\s+(list|create|run|stop|status|delete)(\s+(.+))?$",
    );
    // Agnostic crew management
    r(
        "agnostic_run_crew",
        r"(?i)^agnostic\s+(run[\s_]?crew|crew[\s_]?run)\s+(.+?)(\s+(?:preset|using)\s+(.+))?$",
    );
    r(
        "agnostic_crew_status",
        r"(?i)^agnostic\s+crew\s+(status|check)\s+(\S+)$",
    );
    r(
        "agnostic_list_presets",
        r"(?i)^agnostic\s+(list\s+)?presets(\s+(.+))?$",
    );
    r(
        "agnostic_list_definitions",
        r"(?i)^agnostic\s+(list\s+)?(definitions|agents)(\s+(.+))?$",
    );
    r(
        "agnostic_create_agent",
        r"(?i)^agnostic\s+create\s+agent\s+(\S+)\s+(.+?)(?:\s+role\s+(.+))?$",
    );
    // Delta additional
    r(
        "delta_branches",
        r"(?i)^delta\s+(branch|branches)\s+(list|create|delete|protect|info)(\s+(.+))?$",
    );
    r(
        "delta_review",
        r"(?i)^delta\s+(review|reviews)\s+(request|approve|reject|comment|list)(\s+(.+))?$",
    );
    // Aequi additional
    r(
        "aequi_invoices",
        r"(?i)^aequi\s+(invoice|invoices)\s+(create|list|send|void|status)(\s+(.+))?$",
    );
    r(
        "aequi_reports",
        r"(?i)^aequi\s+(report|reports)\s+(pnl|balance[\s_]?sheet|cash[\s_]?flow|summary)(\s+(?:period|for)\s+(.+))?$",
    );
    // Agnostic additional
    r(
        "agnostic_coverage",
        r"(?i)^agnostic\s+(coverage|cov)\s+(summary|detail|diff|trend)(\s+(.+))?$",
    );
    r(
        "agnostic_schedule",
        r"(?i)^agnostic\s+(schedule|schedules)\s+(create|list|delete|pause|resume)(\s+(.+))?$",
    );
    // Shruti additional
    r(
        "shruti_plugins",
        r"(?i)^shruti\s+(plugin|plugins)\s+(list|load|unload|scan|info)(\s+(.+))?$",
    );
    r(
        "shruti_ai",
        r"(?i)^shruti\s+ai\s+(mix[\s_]?suggest|master|stem[\s_]?split|denoise|transcribe|generate)(\s+(.+))?$",
    );
    // Tazama additional
    r(
        "tazama_media",
        r"(?i)^tazama\s+(media|library)\s+(import|list|info|delete|transcode)(\s+(.+))?$",
    );
    r(
        "tazama_subtitles",
        r"(?i)^tazama\s+(subtitle|subtitles|subs)\s+(generate|edit|export|import|list)(\s+(.+))?$",
    );
    // Rasa additional
    r(
        "rasa_batch",
        r"(?i)^rasa\s+batch\s+(resize|convert|optimize|watermark|list)(\s+(.+))?$",
    );
    r(
        "rasa_templates",
        r"(?i)^rasa\s+(template|templates)\s+(list|create|apply|delete|info)(\s+(.+))?$",
    );
    // Mneme additional
    r(
        "mneme_import",
        r"(?i)^mneme\s+import\s+(file|url|clipboard|bulk|status)(\s+(.+))?$",
    );
    r(
        "mneme_tags",
        r"(?i)^mneme\s+(tag|tags)\s+(list|create|delete|assign|unassign|search)(\s+(.+))?$",
    );
    // Photis additional
    r(
        "photis_boards",
        r"(?i)^photis\s+(board|boards)\s+(list|create|delete|rename|info)(\s+(.+))?$",
    );
    r(
        "photis_notes",
        r"(?i)^photis\s+(note|notes)\s+(create|list|get|delete|search)(\s+(.+))?$",
    );
    // Edge additional
    r(
        "edge_logs",
        r"(?i)^edge\s+(log|logs)\s+(query|tail|search|export)(\s+(.+))?$",
    );
    r(
        "edge_config",
        r"(?i)^edge\s+(config|configuration)\s+(get|set|list|reset)(\s+(.+))?$",
    );
    p
});
